PUBLIC_SRCS = [
  'AbstractBuildStamp.java',
  'AbstractVersionControlStats.java',
  'VersionControlBuckConfig.java',
  'VersionControlCmdLineInterface.java',
  'VersionControlCmdLineInterfaceFactory.java',
  'VersionControlCommandFailedException.java',
  'VersionControlStatsEvent.java',
  'VersionControlStatsGenerator.java',
  'NoOpCmdLineInterface.java',
]

java_immutables_library(
  name = 'versioncontrol',
  srcs = PUBLIC_SRCS,
  immutable_types = [
    'BuildStamp',
    'VersionControlStats',
  ],
  tests = [
    '//test/com/facebook/buck/util/versioncontrol:versioncontrol',
  ],
  autodeps = True,
  visibility = [
    'PUBLIC',
  ],
)

java_library(
  name = 'impl',
  srcs = glob(['*.java'], excludes = PUBLIC_SRCS),
  tests = [
    '//test/com/facebook/buck/util/versioncontrol:versioncontrol',
  ],
  autodeps = True,
  visibility = [
    '//src/com/facebook/buck/cli:cli',
    '//src/com/facebook/buck/step:step',
   '//test/com/facebook/buck/util/versioncontrol/...',
  ],
)
