standard_java_library(
  immutable_types = [
    'ExecutionContext',
  ],
#   deps = [
#     '//src/com/facebook/buck/util/versioncontrol:impl',
#   ],
  tests = [
    '//test/com/facebook/buck/step:step',
  ],
)
